name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: "0"
  CARGO_PROFILE_TEST_DEBUG: "0"
  CARGO_NET_RETRY: "10"
  RUSTUP_MAX_RETRIES: "10"
  RUST_BACKTRACE: short

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install Rust stable
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install Rust stable
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: https://github.com/Swatinem/rust-cache@v2
        with:
          shared-key: workspace
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install Rust stable
        uses: https://github.com/dtolnay/rust-toolchain@stable

      - uses: https://github.com/Swatinem/rust-cache@v2
        with:
          shared-key: workspace
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Build
        run: cargo build --workspace --all-targets --all-features --locked

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install Rust stable
        uses: https://github.com/dtolnay/rust-toolchain@stable

      - uses: https://github.com/Swatinem/rust-cache@v2
        with:
          shared-key: workspace
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install nextest
        uses: https://github.com/taiki-e/install-action@nextest

      - name: Test
        run: cargo nextest run --workspace --all-features --locked

  shear:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install Rust stable
        uses: https://github.com/dtolnay/rust-toolchain@stable

      - uses: https://github.com/Swatinem/rust-cache@v2
        with:
          shared-key: workspace
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install cargo-shear
        uses: https://github.com/taiki-e/install-action@v2
        with:
          tool: cargo-shear

      - name: Cargo Shear
        run: cargo shear
