[package]
name = "musicbrainz"
version.workspace = true
edition.workspace = true

[[example]]
name = "lookup"
required-features = []

[dependencies]
backon = "1.6.0"
governor = "0.6"
musicbrainz_rs = "0.12.0"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt"] }
which = "8"

[dev-dependencies]
clap = { version = "4", features = ["derive", "env"] }
reqwest = "0.12"
url = "2.5.8"
