name: Clippy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Shared Rust setup
        uses: ./.github/actions/rust-setup

      - name: Run clippy
        run: just check-clippy

